# Generated by Django 5.2 on 2025-05-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('guest_count', models.PositiveIntegerField()),
                ('reservation_time', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
